spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gdg_study # ?????? URL
    username: root
    password: junyeon123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # ??? ?? ?? ?? (create, update, validate, none ? ??)
      show-sql: true  # SQL ??? ??? ??
    properties:
      hibernate:
      format_sql: true  # SQL? ???? ??